-- ============================================================
-- NEON://DIARY — 数据库重建 Schema（迁移包内附）
-- ============================================================
--
-- 性质声明（重要）
-- ------------------------------------------------------------
-- 本文件**不是** WorkBuddy 平台的原生 DDL 导出（平台不提供该通道），
-- 而是依据以下两个来源**重建**的参考 DDL：
--   ① app/js/cloud.js 中完整记录的表结构/约束/RLS 语义（该文件的注释
--      就是当初开发时的结构档案，字段名、CHECK 数值、RLS 规则均在其内）
--   ② db/seed/*-rows.json 实测行的字段形态（2026-09-30 匿名导出）
-- 列的类型细节（text vs varchar）可能与原库有出入，但**语义一致**：
-- 应用代码（app/js/cloud.js）按本文档的结构即可正常工作。
--
-- 目标平台：PostgreSQL + PostgREST（Supabase 完全适用；auth.uid() 为
-- Supabase 内置函数。换其他平台需要自建等效的 current-user-id 函数）。
--
-- 用法：把全文粘进 Supabase SQL Editor 执行，或 psql -f schema.sql。
--       之后按 db/README.md 导入 seed 数据。
-- ============================================================

-- ------------------------------------------------------------
-- 0) 前置：auth.uid()
--    PostgREST 风格平台通过 JWT 注入当前用户 id。
--    Supabase 自带 auth.uid()（返回 uuid）；
--    原平台返回 text，故 owner_id 列全是 text（见各表注释）。
-- ------------------------------------------------------------

-- ------------------------------------------------------------
-- 1) posts — 文章
-- ------------------------------------------------------------
create table if not exists posts (
  id          bigint generated by default as identity primary key,
  owner_id    text not null default auth.uid()::text,   -- ⚠ text，不是 uuid
  owner_name  text,                                     -- 展示用署名（登录用户名/昵称）
  title       text not null,
  summary     text,
  content     text not null default '',                 -- Markdown 正文
  tags        jsonb not null default '[]'::jsonb,       -- 字符串数组
  cover_ref   text,                                     -- 'cloudimg://N' 或外链
  status      text not null default 'draft'
              check (status in ('draft', 'published')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()        -- 应用层写回（cloud.js update 时传）
);

alter table posts enable row level security;

-- 已发布内容：所有人可读
create policy posts_select_published on posts
  for select using (status = 'published');

-- 作者：可读含草稿在内的全部自己的文章
create policy posts_select_own on posts
  for select to authenticated using (owner_id = auth.uid()::text);

create policy posts_insert_own on posts
  for insert to authenticated with check (owner_id = auth.uid()::text);

create policy posts_update_own on posts
  for update to authenticated
  using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);

create policy posts_delete_own on posts
  for delete to authenticated using (owner_id = auth.uid()::text);

create index if not exists posts_status_created_idx on posts (status, created_at desc);
create index if not exists posts_owner_idx on posts (owner_id);
create index if not exists posts_tags_gin_idx on posts using gin (tags);  -- 标签过滤 (@>)

-- ------------------------------------------------------------
-- 2) post_images — 图片（base64 存库，不走对象存储）
--    为什么存库：云存储只服务登录用户，而博客图片必须匿名可读。
--    体积约束来自库层 CHECK（见下），客户端上传管线会先压缩
--    （app/js/cloud.js 的 compressImage：data ≤ 3.4M 字符、thumb ≤ 380K）。
-- ------------------------------------------------------------
create table if not exists post_images (
  id           bigint generated by default as identity primary key,
  owner_id     text not null default auth.uid()::text,  -- ⚠ text（与 posts.owner_id 一致）
  content_type text not null default 'image/jpeg',
  data         text not null check (length(data) <= 3600000),          -- 展示版 base64（纯 base64，无 data: 前缀）
  thumb        text check (thumb is null or length(thumb) <= 400000),  -- 缩略图 base64
  width        int,
  height       int,
  size_bytes   bigint,                                  -- 原始文件字节数（压缩前）
  storage_path text,                                    -- 云存储旧方案遗留，可空
  created_at   timestamptz not null default now()
);

alter table post_images enable row level security;

-- ⚠ 已发布的图片经视图 public_images 对匿名开放；
--    基表匿名 SELECT 收回（防枚举 owner_id 等元信息）。
create policy images_select_own on post_images
  for select to authenticated using (owner_id = auth.uid()::text);

create policy images_insert_own on post_images
  for insert to authenticated with check (owner_id = auth.uid()::text);

create policy images_update_own on post_images
  for update to authenticated
  using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);

create policy images_delete_own on post_images
  for delete to authenticated using (owner_id = auth.uid()::text);

create index if not exists post_images_owner_idx on post_images (owner_id);

-- 匿名读通道：只暴露展示必需字段（不含 owner_id / storage_path）
create or replace view public_images as
  select id, content_type, data, thumb, width, height, size_bytes, created_at
  from post_images;

-- ------------------------------------------------------------
-- 3) radio_tracks — 电台（音频以 data URL 存库）
--    为什么存库：见 cloud.js 的血泪注释 —— 云存储只服务登录用户，
--    与「所有人可听」互斥；改存库 + 公开视图后匿名可播。
--    代价：base64 比二进制大 33%、整首一次性传输、单曲上限 24MB
--    （库层 CHECK 取 36,000,000 字符 ≈ 贴上限留 7% 余量）。
-- ------------------------------------------------------------
create table if not exists radio_tracks (
  id           bigint generated by default as identity primary key,
  owner_id     text default auth.uid()::text,           -- ⚠ text
  title        text not null,
  artist       text,
  album        text,
  data         text check (data is null or length(data) <= 36000000),  -- ⚠ data URL 全文（含 data:...;base64, 前缀）
  storage_path text,                                    -- 旧（云存储）方案遗留，新纪录一律 null
  duration_sec int,
  size_bytes   bigint,                                  -- 二进制字节数（非 base64 长度）
  mime         text,
  cover_url    text,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now()
);

alter table radio_tracks enable row level security;

-- 读全开（含匿名）—— 这是「所有人可听」的实现基础
create policy radio_select_all on radio_tracks
  for select using (true);

create policy radio_insert_own on radio_tracks
  for insert to authenticated with check (owner_id = auth.uid()::text);

create policy radio_update_own on radio_tracks
  for update to authenticated
  using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);

create policy radio_delete_own on radio_tracks
  for delete to authenticated using (owner_id = auth.uid()::text);

create index if not exists radio_tracks_order_idx on radio_tracks (sort_order, id);

-- 读取视图：含 data（播放）与 has_data（列表判断"能不能播"而不拉 data）。
-- ⚠ has_data 是**视图算出来的列**，基表没有 —— 写路径（INSERT/UPDATE）
--    绝不能引用它（PostgREST 会报 42703，v2.9.2 事故的根源）。
create or replace view public_radio as
  select id, title, artist, album, mime, data, duration_sec, size_bytes,
         sort_order, cover_url, (data is not null) as has_data, created_at
  from radio_tracks;

-- ------------------------------------------------------------
-- 4) error_logs — 前端错误上报（脱敏后入库）
--    ⚠ 与 posts 不同：owner_id 是 **uuid**（历史设计，platform 差异已固化）。
-- ------------------------------------------------------------
create table if not exists error_logs (
  id         bigint generated by default as identity primary key,
  kind       text,                                      -- 'error' | 'rejection' | 'manual'
  build      text,                                      -- 前端 BUILD_ID
  message    text,                                      -- 已脱敏（scrub：URL/邮箱/token 抹除）
  source     text,
  lineno     int,
  colno      int,
  path       text,
  ua         text,
  owner_id   uuid default auth.uid()::uuid,             -- ⚠ uuid（与 posts.owner_id 的 text 不同）
  created_at timestamptz not null default now()
);

alter table error_logs enable row level security;

-- 任何人可上报（匿名上报归属为 NULL —— 匿名本就没有身份，设计使然）
create policy err_insert_any on error_logs
  for insert with check (true);

-- 仅本人可读自己的错误
create policy err_select_own on error_logs
  for select to authenticated using (owner_id::text = auth.uid()::text);

-- 刻意不建 UPDATE / DELETE 策略：日志只可追加（cloud.js 的授权设计）

-- ------------------------------------------------------------
-- 5) 权限（GRANT）
--    Supabase 惯例：grant 给 anon / authenticated，行级由 RLS 控制。
-- ------------------------------------------------------------
grant select on public_images to anon, authenticated;      -- 匿名读图（走视图）
grant select on public_radio  to anon, authenticated;      -- 匿名听歌（走视图）

grant select, insert, update, delete on posts        to authenticated;
grant select, insert, update, delete on post_images  to authenticated;
grant select, insert, update, delete on radio_tracks to anon, authenticated;
grant insert on error_logs to anon, authenticated;
grant select on error_logs to authenticated;

-- ------------------------------------------------------------
-- 6) 导入种子数据后必须执行（重置自增序列，防主键冲突）
-- ------------------------------------------------------------
-- select setval(pg_get_serial_sequence('posts','id'),        coalesce((select max(id) from posts),1));
-- select setval(pg_get_serial_sequence('post_images','id'),  coalesce((select max(id) from post_images),1));
-- select setval(pg_get_serial_sequence('radio_tracks','id'), coalesce((select max(id) from radio_tracks),1));
